### ISSUE TITLE
References for MoE regression.

### ISSUE THREAD

**Issue by ostwalprasad** [AlexanderFabisch/gmr#15]
Hello!

Could you provide references for Mixtures of Experts Regression? Like a book/paper to refer algorithm from which it was implemented.

Thanks!

**Comment by AlexanderFabisch** [comment]
Hi,

GMR is one of those algorithms that is used in many publications without a clear main reference. Here are some publications:

* [discussion of MoE for supervised problems, same algorithm, different name](https://papers.nips.cc/paper/767-supervised-learning-from-incomplete-data-via-an-em-approach) (section 4.1, 1993)
* [first time I saw the term Gaussian Mixture Regression](https://www.cs.utexas.edu/users/sniekum/classes/RLFD-F15/papers/Calinon07.pdf) (Section V.D, 2007)
* [survey about regression algorithms](https://hal.archives-ouvertes.fr/hal-01162281/document) (section 4.5, 2015)

**Comment by ostwalprasad** [comment]
These links were quite helpful. Thank you!

**Comment by AlexanderFabisch** [comment]
You're welcome. I also added those references to the readme.
