### ISSUE TITLE
Need a reference to Multivariate GMR sample dataset

### ISSUE THREAD

**Issue by solomonmanuelraj** [AlexanderFabisch/gmr#17]
Hi Alex,
Want to solve multivariate regression problem using mixed density network. Need a reference for a open source downloable dataset.

Thanks in advance

**Comment by AlexanderFabisch** [comment]
Hi @solomonmanuelraj ,

unfortunately, I don't know any good public dataset. I didn't do any research though. If you find one, please let me know. I would be happy to integrate it as an example for this library.

**Comment by AlexanderFabisch** [comment]
Apart from that, it is possible to generate your own. In robotics we have the problem of inverse kinematics: when I want to move to some position, how do I have to set my joint angles. There are often multiple solutions. You can create a dataset, for example, with [pybullet](https://pybullet.org/wordpress/) by setting some random joints and then measuring the position of the robot's end-effector.

**Comment by solomonmanuelraj** [comment]
Thanks Alex. I will try to go through package
