### ISSUE TITLE
GMM.means and GMM.covariances have different number of components

### ISSUE THREAD

**Issue by rocreguant** [AlexanderFabisch/gmr#2]
Once the model is trained GMM.means has the number of components (n_components, n_features) but GMM.covariances seem to have the number of training points (n_training_points, n_features, n_features).
Can it be that even though the len(covariance) == n_training_points, the first points belong to the n_components? Because after reading the code it seems that works but the algorithms take only the first points ignoring the rest.

**Comment by AlexanderFabisch** [comment]
Hi,

I can't see how this could happen. Can you give me a simple example?

**Comment by rocreguant** [comment]
Through the training, not on the class creation

**Comment by AlexanderFabisch** [comment]
That should not happen, see [here](https://github.com/AlexanderFabisch/gmr/blob/master/gmr/gmm.py#L84)

**Comment by rocreguant** [comment]
Agree, it does not make any sense to me.
Thanks! :)

**Comment by rocreguant** [comment]
One quick question. Is there a quick way to get the standard deviation/variance from the prediction?

**Comment by AlexanderFabisch** [comment]
You cannot directly get the variance from the prediction. This is not really straightforward. However, you can call GMM.condition to get the conditional GMM p(y|x). Than you could compute the responsibilities for the prediction for each component and take the covariance of the Gaussian distribution with the highest responsibility.

**Comment by rocreguant** [comment]
Thanks! It worked wonders!
