### ISSUE TITLE
Scikit-learn RegressionMixin

### ISSUE THREAD

**Issue by mralbu** [AlexanderFabisch/gmr#27]
Hi, Alexander!
First of all, thanks for this package, it is really awesome! In particular, I appreciate the posterior sampling features.
Do you think a scikit-learn RegressorMixin could be a good additional feature?
I think it could be useful for integration with Pipelines and other scikit-learn tooling.

I made an attempt at it on this branch: [GMMRegression](https://github.com/mralbu/gmr/commit/68cf2f1ebec8aa0fbc8ee7e8134ffd75fcaf2a8b)

Please let me know if I can be of help implementing it.

**Comment by mralbu** [comment]
I've noticed that sometimes the fitted covariances are not all [positive semi-definite](https://en.wikipedia.org/wiki/Definite_symmetric_matrix#:~:text=In%20statistics%2C%20the%20covariance%20matrix,linear%20function%20of%20the%20others.), and that sometimes predictions come out as `np.nan.`
I wrote the gist bellow to illustrate this, using the branch [GMMRegression](https://github.com/mralbu/gmr/commit/68cf2f1ebec8aa0fbc8ee7e8134ffd75fcaf2a8b).

```python

import numpy as np
from sklearn.datasets import load_boston
from sklearn.model_selection import cross_validate

from gmr import GMM, GMMRegression

X, y = load_boston(return_X_y=True)

np.random.seed(42)

cross_validate(GMMRegression(n_components=2), X, y)
>> {'fit_time': array([0.00853992, 0.00294971, 0.00394225, 0.00434303, 0.00185752]),
>>  'score_time': array([0.10137773, 0.08251572, 0.07629395, 0.07693887, 0.08095694]),
>>  'test_score': array([       nan, 0.77102495, 0.58159883, 0.0768928 ,        nan])}

gmr = GMMRegression(n_components=2)
gmr.fit(X, y)

def is_pos_def(x):
    return np.all(np.linalg.eigvals(x) >= 0)

print([is_pos_def(sigma) for sigma in gmr.gmm.covariances])
>> [False, True]
````

**Comment by AlexanderFabisch** [comment]
Hi Marcelo

> Do you think a scikit-learn RegressorMixin could be a good additional feature?

That might be a very useful extension. I have one concern. Currently, sklearn is an optional dependency. I’d like to keep it like that. That means the regressor should be in another file and importing it without sklearn should print a warning. I could make some additional comments if you open a pull request.

> I've noticed that sometimes the fitted covariances are not all positive semi-definite, and that sometimes predictions come out as np.nan.
I wrote the gist bellow to illustrate this, using the branch GMMRegression.

Very useful test case. I’ll take a look at it later this day.

**Comment by AlexanderFabisch** [comment]
>  I wrote the gist bellow to illustrate this, using the branch [GMMRegression](https://github.com/mralbu/gmr/commit/68cf2f1ebec8aa0fbc8ee7e8134ffd75fcaf2a8b).

I don't know yet why this happens, but the priors seem to evaluate to zeros in GMM.condition. A workaround for this is

```python
        priors_sum = priors.sum()
        if priors_sum <= 0.0:
            priors = np.ones_like(priors) / float(len(priors))
        else:
            priors /= priors_sum
```

Maybe that is already the best possible solution, but this would need further investigation.

**Comment by AlexanderFabisch** [comment]
See #28 for my current progress in fixing the numerical issues that you had. I'd recommend to use `GMM.from_samples(..., oracle_approximating_shrinkage=True)` in this case, which is only available in the new pull request.

**Comment by mralbu** [comment]
I moved the additional class GMMRegression to a separate module in [GMMRegression](https://github.com/mralbu/gmr/commit/714cd94670d6625cb963e417aa18505dc4e4be0c). I was not sure of the proper way to warn the user, so my changes may need several adjustments. Please let me know if you think it would be worth it, and I will start a pull request.
I've attempted to build a more tightly coupled scikit-learn RegressorMixin in [scikit-lego](https://github.com/mralbu/scikit-lego/commit/05bb1aa1bf5460c203d4518a4ecbe0db834fa7a4), which already has a GMMClassifier method, reusing many of the sklearn.mixture.GaussianMixture methods. I'm considering opening a pull request in scikit-lego as well.
I will continue to watch and try to use gmr, as I am interested in some of it's additional features. I will probably work on an application of gmr in my line of work during the next week, and will let you know if I have additional comments on these issues.

**Comment by AlexanderFabisch** [comment]
> Please let me know if you think it would be worth it, and I will start a pull request.

Yes, this would definitely be a nice feature for this library. We can discuss details in the pull request.

> I will continue to watch and try to use gmr, as I am interested in some of it's additional features. I will probably work on an application of gmr in my line of work during the next week, and will let you know if I have additional comments on these issues.

Don't hesitate to open new issues. It's better for me to track than writing everything in this issue. :)

**Comment by AlexanderFabisch** [comment]
I guess the main reason why sklearn's GaussianMixture produces better results is their implementation of the expectation step: https://github.com/scikit-learn/scikit-learn/blob/138da7ea911274f34d28849337c2768d7e3a7a96/sklearn/mixture/_base.py#L462

**Comment by AlexanderFabisch** [comment]
#30 , I will close this issue now.
