### ISSUE TITLE
Question: why maintaining this code aside sklearn mixture GMM ?

### ISSUE THREAD

**Issue by show0k** [AlexanderFabisch/gmr#3]
Hi,
The main part of this code is present or rewrited in GMM mixture in scikit-learn. Is there any reason to continue to develop it instead of modifying the sklearn version ?

**Comment by AlexanderFabisch** [comment]
Hi, some features of this library do not fit the sklearn API (conditioning, marginalization). There was a discussion on the sklearn mailing list some month ago.

**Comment by show0k** [comment]
ok, I think you should highlight differences between both implementations because this is not clear for lambda users :)

**Comment by AlexanderFabisch** [comment]
I had to google the term 'lambda user'. :) Can you make a suggestion where to put the explanation?

**Comment by show0k** [comment]
> I had to google the term 'lambda user'. 

Sorry, it must be used more often in French than in English/Germain! 
> Can you make a suggestion where to put the explanation?

A simple note in the README.rst file would be already great.

**Comment by AlexanderFabisch** [comment]
See  c68a014
