### ISSUE TITLE
Error when trying first example

### ISSUE THREAD

**Issue by MetaDev** [AlexanderFabisch/gmr#4]
This is probably a very basic mistake. But I can't seem to run the example (after installing with pip).
I get the error:

  File "/Users/Harald/anaconda/lib/python3.4/site-packages/gmr/__init__.py", line 1, in <module>
    from mvn import MVN, plot_error_ellipse

ImportError: No module named 'mvn'

I tried cloning the complete repository and run the examples from the source but that didn't help either.

**Comment by AlexanderFabisch** [comment]
Try `pip install --upgrade gmr` now. It should work with Python 3 now.

**Comment by MetaDev** [comment]
I'm still getting the same error. After the pip --upgrade gmr I was still on version 1.0. Installing from master did put it on version 1.1 but still the error remains. I use Python 3.5, could that be it?

**Comment by AlexanderFabisch** [comment]
In your first post it seems to be Python 3.4. I use Python 3.4.3 and it works for me. I cannot reproduce this. Could you help me there?

**Comment by MetaDev** [comment]
I updated to 3.5 due to some issue with other packages and the spyder editor. I'm currently updating all libraries I'll keep you posted, it could be a problem at my side.

**Comment by AlexanderFabisch** [comment]
Maybe I forgot to release it on the Pypi website. You could try both.

**Comment by MetaDev** [comment]
Alright, it's good to go :). I had to restart the IPython console I use  after the install. Thank you very much for your patience.

**Comment by Labulitiolle** [comment]
Hi @AlexanderFabisch ,
This error `No module named 'mvn'` is now occurring again when using py37.
Is there a way to get around it?

Thank you for your help

**Comment by AlexanderFabisch** [comment]
Hi @Labulitiolle . Thanks for reporting. It would be better to open a new issue for this problem. I'll see what I can do.

**Comment by AlexanderFabisch** [comment]
I don't know exactly why this happens. Maybe the PyPI package for Python 3 is not updated. If you clone the repository and run python setup.py it should work.

**Comment by AlexanderFabisch** [comment]
OK, I reuploaded gmr 1.1 to PyPI. I hope it works for you know?

**Comment by Labulitiolle** [comment]
Great, it is working now. 
Thank you for your quick response.
