### ISSUE TITLE
ImportError: No module named utils

### ISSUE THREAD

**Issue by meshiguge** [AlexanderFabisch/gmr#6]
sorry ?

**Comment by meshiguge** [comment]
when run the code in example

**Comment by AlexanderFabisch** [comment]
Which version of Python do you use?

Never had this problem but I might know what could cause it. I just pushed a commit to master. Could you check if it fixes your problem?

**Comment by AlexanderFabisch** [comment]
I'll close this issue because I assume it is solved.
