### ISSUE TITLE
Magnitude issue 

### ISSUE THREAD

**Issue by Labulitiolle** [AlexanderFabisch/gmr#9]
Hi @AlexanderFabisch ,
By going through your algorithm I have noticed that the model cannot predict GMMs when the magnitude of one variable exceeds 1000. 
In my case, this is not too much an issue as my variables can be scaled. But this may be interesting to take a look at. 

Thanks again for your work, GMR should definitely be part of Sklearn...

**Comment by AlexanderFabisch** [comment]
Hi,

this is an issue that seems to be a bit difficult to fix on the algorithm's side. I would recommend to use [sklearn.preprocessing.StandardScaler](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html) on your data if this is an issue.

**Comment by Labulitiolle** [comment]
All right, by curiosity what is causing this issue?

**Comment by AlexanderFabisch** [comment]
I did not fully understand it yet. Maybe it's numerical problem (for example, exp(small value) -> 0 or exp(large value) -> infinity). If you are interested and want to help you can take a look. I would be happy about any support.

**Comment by AlexanderFabisch** [comment]
OK, most likely the covariances have to be initialized differently. Means are already initialized to data points but the covariances are always identity matrices. Their variance should be set to something like (average distance / number of Gaussians) ** 2. I don't know if that will fix it though.

**Comment by Labulitiolle** [comment]
Great, I'll try to have a deeper look at it next weekend.
It also seems like the Gaussians do not fit the data the same way as GMM goes it in the sklearn package.

**Comment by AlexanderFabisch** [comment]
@Labulitiolle Did you have a chance to look into the issue? Meanwhile I also tried some things. See #10

**Comment by Labulitiolle** [comment]
Hi @AlexanderFabisch ,
I am really sorry, it's a bit of a rush theses lately. Your commit seems to be a great improvement. 
It is still on my todos to go through the code, I can't give you a fixed date though...

**Comment by AlexanderFabisch** [comment]
Thanks. I merged it just a few seconds ago.
